language: php

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION="4.3.*"
    - php: 7.4
      env: SYMFONY_VERSION="4.3.*"

cache:
  directories:
    - ~/.composer

before_script:
  - phpenv config-add .travis.php.ini
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist

script:
  - ant

branches:
  only:
    - master
    - develop
    - /^feature\/(.*)$/
    - /^hotfix\/(.*)$/
    - /^bugfix\/(.*)$/

addons:
  apt:
    packages:
      - ant
